spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kiyodb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 4321
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2.client:
      registration:
        google:
          clientId:
          clientSecret:
          scope:
            - email
            - profile

# cors 설정
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret:

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 
    tokenExpiry: 1800000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect

logging.level:
  org.hibernate.SQL: debug