# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: KIYO

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
       distribution: 'temurin'
       java-version: '11'
    
    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        character set server: 'utf8' 
        mysql database: 'kiyodb' 
        mysql user: 'root'
        mysql password: 4321

    - name : make application.yml
      if: contains(github.ref,'develop')
      run: | 
        cd ./src/test/resources
        touch ./application.yml
        echo "${{secrets.PROPERTIES}}" > ./application.yml
      shell : bash
      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    
    - name: Build with Gradle
      run: ./gradlew build
      shell: bash
      
    - name: action-slack
      uses: 8398a7/action-slack@v3
      with: 
        status: ${{ job.status }}
        author_name: Github Action Test # default: 8398a7@action-slack
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL}}
      if: always() 
